version: "3.8"
services:
  temporal:
    image: temporalio/auto-setup:latest
    container_name: temporal
    ports:
      - "7233:7233"
    networks:
      - temporal-network

  temporal-ui:
    image: temporalio/ui:latest
    container_name: temporal-ui
    depends_on:
      - temporal
    ports:
      - "8080:8080"
    networks:
      - temporal-network

networks:
  temporal-network:
    driver: bridge

